name: Release
on:
  workflow_dispatch:
  push:
    branches:
      - master
      - beta
      - "console-release-[0-9]+.[0-9]+.[0-9]+"
    paths-ignore:
      - '.github/**'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          token: ${{ secrets.PAT_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Cache node modules
        id: node-cache
        uses: actions/cache@v2
        with:
            path: node_modules
            key: $ {{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
            restore-keys: |
              $ {{ runner.OS }}-build-
              $ {{ runner.OS }}-

      - name: Install dependencies
        if: steps.node-cache.outputs.cache-hit != 'true'
        run: npm install

      - name: Build
        run: npm run build && npm run css

      - name: Transpile
        run: npm run vue-tsc || npm run tsc-alias

      - name: Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          git config --global http.postBuffer 1048576000
          npm run semantic-release

      - name: Slack
        if: always()
        uses: 8398a7/action-slack@v3.2.0
        with:
          status: ${{job.status}}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          author_name: Github Action Slack
        env:
          SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}
